# Golang CircleCI configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
jobs:
  build:
    docker:
      # specify the version
      - image: cimg/go:1.19.0
      
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go mod download
      - run: go build      
      
  first-job:
    docker:
      - image: ubuntu
    steps:
      - run: echo "this is the first job"
  second-job:
    docker:
      - image: ubuntu
    steps:
      - run: echo "this is the second job"
  third-job:
    docker:
      - image: ubuntu
    steps:
      - run: echo "this is the third job"
      
workflows:
  first-workflow:
    jobs:
      - first-job
      - second-job:
          filters:
            branches:
              only:
                - /.*special/
      - third-job:
          requires:
            - first-job
            - second-job
  second-workflow:
    jobs:
      - build
