# Golang CircleCI configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.14
      
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go mod download
      - run: go build
